# Generated by Django 5.0.3 on 2024-06-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_blog', '0007_alter_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(),
        ),
    ]
