# Generated by Django 5.0.3 on 2024-05-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=50)),
                ('medico', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/servicios')),
                ('horario', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'especialidad',
                'verbose_name_plural': 'especialidades',
            },
        ),
    ]
