# Generated by Django 5.0.2 on 2024-05-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_directorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorio',
            name='imagen',
        ),
    ]
