# Generated by Django 5.0.3 on 2024-04-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_clc', '0003_registroimpresion'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='archivo',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
