# Generated by Django 5.0.3 on 2024-04-03 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_clc', '0004_consulta_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='archivo',
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_consulta/')),
                ('consulta_relacionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_clc.consulta')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='archivos',
            field=models.ManyToManyField(blank=True, to='App_clc.archivo'),
        ),
    ]
