# Generated by Django 5.0.3 on 2024-04-03 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_clc', '0005_remove_consulta_archivo_archivo_consulta_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='consulta_relacionada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_relacionados', to='App_clc.consulta'),
        ),
    ]
