# Generated by Django 5.0.3 on 2024-04-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_clc', '0006_alter_archivo_consulta_relacionada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='archivos',
        ),
        migrations.AddField(
            model_name='consulta',
            name='archivos',
            field=models.FileField(blank=True, upload_to='', verbose_name='Archivo'),
        ),
    ]
