# Generated by Django 5.0.3 on 2024-04-04 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_clc', '0007_remove_consulta_archivos_consulta_archivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField()),
                ('motivo_consulta', models.TextField()),
                ('diagnostico_consulta', models.TextField()),
                ('tratamiento_consulta', models.TextField()),
                ('cirugia_realizada', models.BooleanField(default=False)),
                ('resultado_cirugia', models.TextField(blank=True, null=True)),
                ('archivos_consulta', models.ManyToManyField(blank=True, to='App_clc.archivo')),
                ('documentos', models.ManyToManyField(blank=True, to='App_clc.documento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_clc.paciente')),
            ],
        ),
    ]
