# Generated by Django 5.0.3 on 2024-04-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_clc', '0009_remove_paciente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='proxima_cosulta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
