# Generated by Django 5.0.3 on 2024-04-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_clc', '0010_consulta_proxima_cosulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cedula_pasaporte',
            field=models.CharField(default='default_value', max_length=20),
        ),
    ]
