# Generated by Django 5.0.3 on 2024-04-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_clc', '0012_paciente_sexo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='cedula_pasaporte',
            new_name='cedula_identidad',
        ),
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
