# Generated by Django 5.0.3 on 2024-04-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_clc', '0013_rename_cedula_pasaporte_paciente_cedula_identidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugia',
            name='enfermeros',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='medicos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='personal_externo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='tipo',
            field=models.CharField(choices=[('A', 'Artroscopia'), ('R', 'Reemplazo articular'), ('L', 'Cirugía de ligamentos'), ('C', 'Cirugía de columna'), ('CR', 'Cirugía reconstructiva'), ('CMM', 'Cirugía de mano y muñeca')], default='selecciona', max_length=3),
        ),
    ]
