# Generated by Django 5.0.3 on 2024-04-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_clc', '0015_alter_cirugia_enfermeros_alter_cirugia_medicos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='motivo',
            field=models.CharField(choices=[('V', 'Valoración'), ('PRO', 'Pre Operatorio'), ('PO', 'Post Operatorio'), ('PC', 'Primera cita'), ('SC', 'Segunda cita'), ('TC', 'Tercera cita'), ('CC', 'Cuarta cita'), ('QC', 'Quinta cita'), ('CO', 'Cita Opcional')], default='seleccionar', max_length=3),
        ),
    ]
