# Generated by Django 5.0.3 on 2024-05-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_clc', '0018_alter_consulta_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('ICH', 'Informe clínico hospitalización'), ('ICCE', 'Informe clínico consulta externa'), ('ICE', 'Informe clínico de emergencias'), ('IMAP', 'Informe médico de atención primaria'), ('IRPL', 'Informe de resultados de pruebas de laboratorio'), ('ICH', 'Informe de resultados de pruebas de imagen'), ('ICE', 'Informe de cuidados de enfermeria')], default='seleccionar', max_length=4),
        ),
    ]
