# Generated by Django 5.0.3 on 2024-05-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_clc', '0022_alter_documento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(null=True, upload_to='clinica'),
        ),
    ]
