# Generated by Django 5.0.3 on 2024-06-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_clc', '0025_alter_documento_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='proxima_cosulta',
            new_name='proxima_consulta',
        ),
    ]
