# Generated by Django 5.0.3 on 2024-06-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/entrada_home')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('contenido', models.TextField()),
            ],
            options={
                'verbose_name': 'entrada_home',
                'verbose_name_plural': 'entradas_home',
            },
        ),
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/entradas')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('contenido', models.TextField()),
            ],
            options={
                'verbose_name': 'entrada',
                'verbose_name_plural': 'entradas',
            },
        ),
    ]
