# Generated by Django 5.0.3 on 2024-06-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/mision')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('contenido', models.TextField()),
            ],
            options={
                'verbose_name': 'mision',
                'verbose_name_plural': 'misiones',
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/visiones')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('contenido', models.TextField()),
            ],
            options={
                'verbose_name': 'vision',
                'verbose_name_plural': 'visiones',
            },
        ),
        migrations.DeleteModel(
            name='Entrada_home',
        ),
    ]
