
# Generated by Django 5.0.3 on 2024-05-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_servicios', '0002_alter_servicios_contenido_alter_servicios_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/servicios'),
        ),
    ]
